### ISSUE TITLE
AES-CBC with PKCS#7 padding

### ISSUE THREAD

**Issue by brycx** [r-olm/r-olm#3]
If this isn't directly provided by `openssl`, it would be nice with some official test vectors, or test it against other libraries, in Python for example.

**Comment by akritrime** [comment]
I think we should start moving forward with OpenSSL assuming it has pkcs#7 padding. In the meanwhile, I can write some tests in python and javascript to test it out.

**Comment by brycx** [comment]
I doubt both Python and Javascript are needed. If you can, perhaps test against the C++ Crypto++ lib.

**Comment by akritrime** [comment]
Cool. No problem.

**Comment by brycx** [comment]
Fixed #9. Closing this issue.
